name: Main CI

on: push

jobs:
  Init_and_test:
    name: Init and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.1
        cache: npm
    - name: Initialise npm
      run: npm ci
    - name: Perform Static Analysis with ESLint
      run: npx eslint -o eslint_report.json -f json
      continue-on-error: true
    - name: Create ESLint Annotations
      uses: ataylorme/eslint-annotate-action@v3
      with:
        only-pr-files: false
    - name: Run Jest Tests
      run: npm test
    - name: Build a docker test image
      run: docker build -t trooshack/tekwani-trushik-intro-to-devops-a2:test-latest ./Dockerfile.Test
    - name: Build a docker user image
      run: docker build -t trooshack/tekwani-trushik-intro-to-devops-a2:user-latest ./user.Dockerfile   
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the test image to Docker hub
      run: docker push trooshack/tekwani-trushik-intro-to-devops-a2:test-latest
    - name: Push the user image to Docker hub
      run: docker push trooshack/tekwani-trushik-intro-to-devops-a2:user-latest
